spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

otel:
  exporter:
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
